
name: Deploy

on:
  push: 
    branches:
      - master
      
jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@master
    - name: Install SSH key 
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run deployment scripts

      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ vars.USERNAME }}@${{ vars.HOST }} '
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/*
          cd ${{ vars.DEPLOY_PATH }}
          rm -rf 
          git clone git@github.com:${{ github.repository }} 
          cd ${{ vars.DEPLOY_PATH }}
          echo "OPENAI_KEY=${{ secrets.API_KEY }}" > .env
          echo "PORT=${{ vars.PORT }}" >> .env
          docker compose up -d --build
        '