version: '3'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-test
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant/custom_config.yaml:/qdrant/config/production.yaml
      - ./data/qdrant_storage:/qdrant/storage
